packages:
  - apps/*
  - packages/*

allowBuilds:
  electron-winstaller: false
  esbuild: true
  msgpackr-extract: true

catalog:
  effect: 4.0.0-rc.112
  "@effect/atom-react": 4.0.0-rc.112
  "@effect/platform-node": 4.0.0-rc.112
  "@effect/sql-sqlite-node": 4.0.0-rc.112
  "@effect/vitest": 4.0.0-rc.112
  "@tanstack/react-router": ^1.170.32
  typescript: ^7.0.0
  "@types/node": ^24

minimumReleaseAgeExclude:
  - '@effect/tsgo-darwin-arm64@0.38.0'
  - '@effect/tsgo-darwin-x64@0.38.0'
  - '@effect/tsgo-linux-arm64@0.38.0'
  - '@effect/tsgo-linux-arm@0.38.0'
  - '@effect/tsgo-linux-x64@0.38.0'
  - '@effect/tsgo-win32-arm64@0.38.0'
  - '@effect/tsgo-win32-x64@0.38.0'
  - '@effect/tsgo@0.38.0'
