import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Compiles drizzle-kit's generated SQL into a TypeScript module.
 *
 * The main process is bundled by Vite and shipped inside an Electron package, where reading a
 * `.sql` file relative to the source tree is not reliable. Emitting the statements as a module
 * makes the DDL an ordinary import — bundler-safe, and visible to `tsc` and vitest without a
 * loader plugin.
 *
 * Run via `pnpm db:generate`, which runs drizzle-kit first. The output is a build artifact:
 * checked in so the DDL is reviewable in a diff, never edited by hand.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const migrationsDir = path.join(here, "..", "drizzle");
const outFile = path.join(here, "..", "src", "main", "db", "migrations.generated.ts");

const files = readdirSync(migrationsDir)
  .filter((file) => file.endsWith(".sql"))
  .sort();

const statements = files.flatMap((file) =>
  readFileSync(path.join(migrationsDir, file), "utf8")
    .split("--> statement-breakpoint")
    .map((statement) => statement.trim())
    .filter((statement) => statement.length > 0),
);

const body = statements.map((statement) => `  \`${statement.replaceAll("`", "\\`")}\`,`).join("\n");

writeFileSync(
  outFile,
  `// Generated by \`pnpm db:generate\` from src/main/db/schema.ts. Do not edit.
/* eslint-disable */

/** Every DDL statement for a fresh save file, in dependency-safe creation order. */
export const MIGRATION_STATEMENTS: ReadonlyArray<string> = [
${body}
];
`,
);

console.log(`Wrote ${statements.length} statements from ${files.length} migration file(s).`);
