import {
  CANONICAL_RESEARCH_FIELD_IDS,
  MAX_HIGH_PRIORITY_FIELDS,
  RESEARCH_FIELD_PRIORITY_WEIGHTS,
} from "@bluewave/campaign-engine";
import type {
  ResearchPriorityOutcome,
  ResearchScreenProjection,
} from "../../../shared/research-contract.js";
import { describeRejection } from "../../lib/command-screen-workflow.js";

/**
 * Pure presentation state for the Research & Technology screen
 * (desktop-engine-feature-gate INC-3). A discriminated union over the
 * screen's phases — idle / loading / load-failed / loaded / submitting /
 * submitted / rejected-with-revision — with every transition a pure function
 * of its inputs (no clock, no env, no randomness inside; the transport
 * request identity is generated by the hook and injected as data). All
 * numbers come from the engine projection; the screen never computes
 * authoritative values.
 */
export type ResearchScreenState =
  | ResearchScreenIdle
  | ResearchScreenLoading
  | ResearchScreenLoadFailed
  | ResearchScreenLoaded
  | ResearchScreenSubmitting
  | ResearchScreenSubmitted
  | ResearchScreenRejectedWithRevision;

export interface ResearchScreenIdle {
  readonly kind: "idle";
  readonly revision: number;
}

export interface ResearchScreenLoading {
  readonly kind: "loading";
  readonly revision: number;
}

export interface ResearchScreenLoadFailed {
  readonly kind: "load-failed";
  readonly revision: number;
  readonly message: string;
}

export interface ResearchScreenActiveData {
  readonly revision: number;
  readonly month: ResearchScreenProjection["month"];
  readonly projection: ResearchScreenProjection;
  /** Editable per-field weight draft — seeded from the projection (missing
   * fields default to LOW), mutated only through `setDraftWeight`. */
  readonly draft: FieldWeightsDraft;
  readonly notice: string | null;
}

export interface ResearchScreenLoaded extends ResearchScreenActiveData {
  readonly kind: "loaded";
}

export interface ResearchScreenSubmitting extends ResearchScreenActiveData {
  readonly kind: "submitting";
  readonly pendingTransportRequestId: string;
}

export interface ResearchScreenSubmitted extends ResearchScreenActiveData {
  readonly kind: "submitted";
}

export interface ResearchScreenRejectedWithRevision extends ResearchScreenActiveData {
  readonly kind: "rejected-with-revision";
}

/** One canonical field's edit weight — the DESIGN-20 weight scale {1,2,4},
 * mirrored from `RESEARCH_FIELD_PRIORITY_WEIGHTS` for the picker controls. */
export type ResearchWeight =
  (typeof RESEARCH_FIELD_PRIORITY_WEIGHTS)[keyof typeof RESEARCH_FIELD_PRIORITY_WEIGHTS];

export type FieldWeightsDraft = Readonly<Record<string, number>>;

export function initialResearchScreenState(): ResearchScreenState {
  return { kind: "idle", revision: 0 };
}

export function researchBeginLoading(state: ResearchScreenState): ResearchScreenState {
  return { kind: "loading", revision: state.revision };
}

export function researchLoadSuccess(
  state: ResearchScreenState,
  projection: ResearchScreenProjection,
): ResearchScreenState {
  return {
    kind: "loaded",
    revision: projection.revision,
    month: projection.month,
    projection,
    draft: seedDraft(projection),
    notice: null,
  };
}

export function researchLoadFailure(
  state: ResearchScreenState,
  message: string,
): ResearchScreenState {
  return { kind: "load-failed", revision: state.revision, message };
}

/** Begin a priority submission — the pure machine side of the submit flow.
 * `transportRequestId` comes from the shell (idempotency context), never from
 * the reducer. Only reachable from `loaded`/`submitted`. */
export function researchBeginSubmit(
  state: ResearchScreenState,
  transportRequestId: string,
): ResearchScreenState {
  if (state.kind !== "loaded" && state.kind !== "submitted") return state;
  return {
    kind: "submitting",
    revision: state.revision,
    month: state.month,
    projection: state.projection,
    draft: state.draft,
    pendingTransportRequestId: transportRequestId,
    notice: state.notice,
  };
}

export function researchSubmitSuccess(
  state: ResearchScreenState,
  outcome: ResearchPriorityOutcome,
): ResearchScreenState {
  if (state.kind !== "submitting") return state;
  return {
    kind: "submitted",
    revision: state.revision,
    month: state.month,
    projection: state.projection,
    draft: state.draft,
    notice: `${outcome.commandId} queued — the engine applies these priorities on the next turn advance.`,
  };
}

/**
 * Fold a rejection into the state. A rejection carrying a `currentRevision`
 * (stale optimistic-concurrency — `REVISION_MISMATCH`) moves to
 * `rejected-with-revision`; the screen reacts by refreshing the projection.
 * Any other rejection (engine constraint codes such as
 * `RESEARCH_PRIORITY_CONSTRAINT_VIOLATED`, idempotency conflicts) stays on
 * the loaded state with the engine diagnostics as the notice.
 */
export function researchSubmitRejected(
  state: ResearchScreenState,
  rejection: {
    readonly reason: string;
    readonly diagnostics: readonly string[];
    readonly currentRevision?: number;
  },
): ResearchScreenState {
  if (state.kind !== "submitting" && state.kind !== "submitted") return state;
  const notice = describeRejection(
    rejection.reason,
    rejection.diagnostics,
    rejection.currentRevision,
  );
  if (rejection.currentRevision !== undefined) {
    return {
      kind: "rejected-with-revision",
      revision: rejection.currentRevision,
      month: state.month,
      projection: state.projection,
      draft: state.draft,
      notice,
    };
  }
  return {
    kind: "loaded",
    revision: state.revision,
    month: state.month,
    projection: state.projection,
    draft: state.draft,
    notice,
  };
}

export function researchTransportFailure(
  state: ResearchScreenState,
  message: string,
): ResearchScreenState {
  if (state.kind !== "submitting" && state.kind !== "submitted") return state;
  return {
    kind: "loaded",
    revision: state.revision,
    month: state.month,
    projection: state.projection,
    draft: state.draft,
    notice: `TRANSPORT_FAILURE: ${message}`,
  };
}

/** Seed the editable draft from the projection: every canonical field present,
 * values clamped to the DESIGN-20 weight scale (anything else the compiler
 * emitted defaults to LOW — the picker's baseline, re-validated by the engine
 * on submit). */
export function seedDraft(projection: ResearchScreenProjection): FieldWeightsDraft {
  const draft: Record<string, number> = {};
  for (const field of CANONICAL_RESEARCH_FIELD_IDS) {
    const weight = projection.fieldPriorities[field];
    draft[field] = isWeightValue(weight) ? weight : RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW;
  }
  return Object.freeze(draft);
}

export function setDraftWeight(
  draft: FieldWeightsDraft,
  fieldId: string,
  weight: FieldWeightOption,
): FieldWeightsDraft {
  // INC-5: 5-HIGH cap — raising a 6th field to HIGH is rejected (no silent
  // redistribution). The caller must first lower another HIGH field.
  if (
    weight === RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH &&
    draft[fieldId] !== RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH
  ) {
    const currentHigh = CANONICAL_RESEARCH_FIELD_IDS.filter(
      (field) => draft[field] === RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH,
    ).length;
    if (currentHigh >= MAX_HIGH_PRIORITY_FIELDS) return draft;
  }
  return Object.freeze({ ...draft, [fieldId]: weight });
}

/** The values the picker toggles between — the DESIGN-20 weight scale. */
export const WEIGHT_OPTIONS: readonly {
  readonly weight: FieldWeightOption;
  readonly label: string;
}[] = [
  { weight: RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH, label: "High" },
  { weight: RESEARCH_FIELD_PRIORITY_WEIGHTS.MEDIUM, label: "Med" },
  { weight: RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW, label: "Low" },
];

export type FieldWeightOption =
  | typeof RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH
  | typeof RESEARCH_FIELD_PRIORITY_WEIGHTS.MEDIUM
  | typeof RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW;

function isWeightValue(value: number | undefined): value is FieldWeightOption {
  return (
    value === RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH ||
    value === RESEARCH_FIELD_PRIORITY_WEIGHTS.MEDIUM ||
    value === RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW
  );
}

/** The payload record for `setResearchPriorityCommand`, in canonical field
 * order (stable for idempotency comparison). */
export function draftToPriorities(draft: FieldWeightsDraft): Record<string, number> {
  const payload: Record<string, number> = {};
  for (const field of CANONICAL_RESEARCH_FIELD_IDS) {
    payload[field] = draft[field] ?? RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW;
  }
  return payload;
}

/** How many fields are currently set to HIGH — the engine's command
 * validation requires 1..5 (MAX_HIGH_PRIORITY_FIELDS). */
export function draftHighCount(draft: FieldWeightsDraft): number {
  return CANONICAL_RESEARCH_FIELD_IDS.filter(
    (field) => draft[field] === RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH,
  ).length;
}

/** A draft is submittable when every canonical field carries a weight from
 * the {1,2,4} scale and at least one field is HIGH (mirrors the engine's
 * `SetResearchPriority` lifecycle validation). The engine also requires
 * `highCount <= MAX_HIGH_PRIORITY_FIELDS` — the UI's 5-HIGH cap (spec §10,
 * INC-5). */
export function draftIsSubmittable(draft: FieldWeightsDraft): boolean {
  const highCount = draftHighCount(draft);
  return (
    CANONICAL_RESEARCH_FIELD_IDS.every((field) => isWeightValue(draft[field])) &&
    highCount >= 1 &&
    highCount <= MAX_HIGH_PRIORITY_FIELDS
  );
}

/** Whether the editable draft diverges from the last committed projection —
 * the renderer-only "unsaved changes" signal (spec §17). Only the research
 * allocation surface has a draft, so this is the one place the indicator is
 * meaningful. */
export function isDraftDirty(
  projection: ResearchScreenProjection,
  draft: FieldWeightsDraft,
): boolean {
  for (const field of CANONICAL_RESEARCH_FIELD_IDS) {
    const committed = projection.fieldPriorities[field] ?? RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW;
    const edited = draft[field] ?? RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW;
    if (committed !== edited) return true;
  }
  return false;
}

/** Pure largest-remainder proportional split over the draft weights, mirroring
 * `packages/phase-engine/src/research.ts:largestRemainderAllocation` (spec §10
 * "projected monthly progress"). `researchBudget` is the UI budget number; the
 * engine's `computeResearchResources` is the identity (BP 10_000), so the
 * budget is used directly as resources. Returns a per-field allocation that
 * sums exactly to `researchBudget` (when >0 and at least one weight-bearing
 * field). */
export function deriveProjectedResearchAllocations(
  researchBudget: number,
  draft: FieldWeightsDraft,
): Readonly<Record<string, number>> {
  const result: Record<string, number> = {};
  for (const field of CANONICAL_RESEARCH_FIELD_IDS) {
    result[field] = 0;
  }
  if (!Number.isSafeInteger(researchBudget) || researchBudget <= 0) return Object.freeze(result);

  const weights: [string, number][] = [];
  for (const field of CANONICAL_RESEARCH_FIELD_IDS) {
    const weight = draft[field];
    if (
      weight === RESEARCH_FIELD_PRIORITY_WEIGHTS.HIGH ||
      weight === RESEARCH_FIELD_PRIORITY_WEIGHTS.MEDIUM ||
      weight === RESEARCH_FIELD_PRIORITY_WEIGHTS.LOW
    ) {
      if (weight > 0) weights.push([field, weight]);
    }
  }
  if (weights.length === 0) return Object.freeze(result);

  const totalWeight = weights.reduce((sum, [, w]) => sum + w, 0);
  if (totalWeight <= 0) return Object.freeze(result);

  let allocated = 0;
  const remainders: [string, number][] = [];
  for (const [fieldId, weight] of weights) {
    const raw = (weight / totalWeight) * researchBudget;
    const floorShare = Math.floor(raw);
    result[fieldId] = floorShare;
    allocated += floorShare;
    remainders.push([fieldId, raw - floorShare]);
  }
  let remaining = researchBudget - allocated;
  remainders.sort((a, b) => b[1] - a[1]);
  for (const [fieldId] of remainders) {
    if (remaining <= 0) break;
    result[fieldId] = (result[fieldId] ?? 0) + 1;
    remaining -= 1;
  }
  return Object.freeze(result);
}
