import type {
  DiplomacyScreenProjection,
  DiplomacyCommandBody,
} from "../../../shared/diplomacy-contract.js";
import { describeRejection } from "../../lib/command-screen-workflow.js";

/**
 * Pure presentation state for the Diplomacy & War screen
 * (desktop-diplomacy-war INC-3). A discriminated union over the screen's
 * phases — idle / loading / load-failed / loaded / submitting / submitted /
 * rejected-with-revision — with every transition a pure function of its
 * inputs (no clock, no env, no randomness inside; the transport request
 * identity is generated by the hook and injected as data). All numbers come
 * from the engine projection; the screen never computes authoritative values.
 *
 * The screen issues ONE engine command at a time (spec D2) — the reducer
 * holds a single `draftCommand` and legal-action derivation per relation row.
 * The derivation is UI affordance ONLY (which chips to show), never a
 * re-implementation of the engine's validators — the engine is the authority
 * at issue time via `submitDiplomacyCommand`.
 */
export type DiplomacyScreenState =
  | DiplomacyScreenIdle
  | DiplomacyScreenLoading
  | DiplomacyScreenLoadFailed
  | DiplomacyScreenLoaded
  | DiplomacyScreenSubmitting
  | DiplomacyScreenSubmitted
  | DiplomacyScreenRejectedWithRevision;

export interface DiplomacyScreenIdle {
  readonly kind: "idle";
  readonly revision: number;
}

export interface DiplomacyScreenLoading {
  readonly kind: "loading";
  readonly revision: number;
}

export interface DiplomacyScreenLoadFailed {
  readonly kind: "load-failed";
  readonly revision: number;
  readonly message: string;
}

/** Shared payload of every data-bearing phase. */
export interface DiplomacyScreenActiveData {
  readonly revision: number;
  readonly month: DiplomacyScreenProjection["month"];
  readonly projection: DiplomacyScreenProjection;
  /** The single pending engine command, or null. */
  readonly draftCommand: DiplomacyDraftCommand | null;
  readonly notice: string | null;
}

export interface DiplomacyScreenLoaded extends DiplomacyScreenActiveData {
  readonly kind: "loaded";
}

export interface DiplomacyScreenSubmitting extends DiplomacyScreenActiveData {
  readonly kind: "submitting";
  readonly pendingTransportRequestId: string;
}

export interface DiplomacyScreenSubmitted extends DiplomacyScreenActiveData {
  readonly kind: "submitted";
}

export interface DiplomacyScreenRejectedWithRevision extends DiplomacyScreenActiveData {
  readonly kind: "rejected-with-revision";
}

/** The 7 B10c command kinds the screen can draft. */
export type DiplomacyActionKind =
  | "DeclareWar"
  | "AcceptPeace"
  | "FormAlliance"
  | "BreakAlliance"
  | "FormNonAggressionPact"
  | "BreakNonAggressionPact"
  | "DeclareBlockade";

/** A single command the player is about to issue. `partnerNationId` is the
 * OTHER nation for pair actions (for AcceptPeace: the opposing war side). */
export interface DiplomacyDraftCommand {
  readonly kind: DiplomacyActionKind;
  readonly partnerNationId: string;
  readonly warId?: string;
  readonly areaId?: string;
}

export function initialDiplomacyScreenState(): DiplomacyScreenState {
  return { kind: "idle", revision: 0 };
}

export function diplomacyBeginLoading(state: DiplomacyScreenState): DiplomacyScreenState {
  return { kind: "loading", revision: state.revision };
}

export function diplomacyLoadSuccess(
  _state: DiplomacyScreenState,
  projection: DiplomacyScreenProjection,
): DiplomacyScreenState {
  return {
    kind: "loaded",
    revision: projection.revision,
    month: projection.month,
    projection,
    draftCommand: null,
    notice: null,
  };
}

export function diplomacyLoadFailure(
  state: DiplomacyScreenState,
  message: string,
): DiplomacyScreenState {
  return { kind: "load-failed", revision: state.revision, message };
}

/** Legal-action affordance for one relations row — derived from the projected
 * relation/nap state ONLY (`declareWar` enabled unless `at_war`, alliance/NAP
 * form/break on the matching relation). This drives which chips render; the
 * engine's own `CommandLifecycle.validate()` remains the authority at issue
 * time (spec D1) — nothing here re-implements it. */
export function diplomacyLegalActions(row: {
  readonly relation: DiplomacyScreenProjection["relations"][number]["relation"];
  readonly nap: boolean;
}): DiplomacyActionKind[] {
  const actions: DiplomacyActionKind[] = [];
  if (row.relation !== "at_war") actions.push("DeclareWar");
  if (row.relation === "neutral") actions.push("FormAlliance");
  if (row.relation === "allied") actions.push("BreakAlliance");
  if (row.relation === "at_war") actions.push("DeclareBlockade");
  if (row.nap) actions.push("BreakNonAggressionPact");
  else if (row.relation !== "at_war") actions.push("FormNonAggressionPact");
  return actions;
}

/** Begin drafting a pair action on a relations row. Only reachable from a
 * data-bearing phase; replaces any prior draft. */
export function diplomacyBeginAction(
  state: DiplomacyScreenState,
  partnerNationId: string,
  kind: DiplomacyActionKind,
): DiplomacyScreenState {
  if (state.kind !== "loaded" && state.kind !== "submitted") return state;
  if (kind === "AcceptPeace") return state;
  const draft: DiplomacyDraftCommand = {
    kind,
    partnerNationId,
    ...(kind === "DeclareBlockade" ? { areaId: state.projection.areas[0]?.areaId } : {}),
  };
  return { ...state, draftCommand: draft, notice: null };
}

/** Draft an AcceptPeace against a player-involved war (Wars card). */
export function diplomacyBeginPeace(
  state: DiplomacyScreenState,
  war: DiplomacyScreenProjection["wars"][number],
): DiplomacyScreenState {
  if (state.kind !== "loaded" && state.kind !== "submitted") return state;
  if (war.status !== "ACTIVE") return state;
  const opponent = war.playerSide === "attacker" ? war.defenderId : war.attackerId;
  return {
    ...state,
    draftCommand: { kind: "AcceptPeace", partnerNationId: opponent, warId: war.warId },
    notice: null,
  };
}

/** Change the area of the currently drafted DeclareBlockade. */
export function diplomacySetBlockadeArea(
  state: DiplomacyScreenState,
  areaId: string,
): DiplomacyScreenState {
  if (state.kind !== "loaded" && state.kind !== "submitted") return state;
  const draft = state.draftCommand;
  if (draft === null || draft.kind !== "DeclareBlockade") return state;
  return { ...state, draftCommand: { ...draft, areaId }, notice: null };
}

export function diplomacyClearDraft(state: DiplomacyScreenState): DiplomacyScreenState {
  if (state.kind !== "loaded" && state.kind !== "submitted") return state;
  return { ...state, draftCommand: null, notice: null };
}

/** Begin a submit — the pure machine side of the flow. `transportRequestId`
 * comes from the shell (idempotency context), never from the reducer. */
export function diplomacyBeginSubmit(
  state: DiplomacyScreenState,
  transportRequestId: string,
): DiplomacyScreenState {
  if (state.kind !== "loaded" && state.kind !== "submitted") return state;
  const draft = state.draftCommand;
  if (draft === null || diplomacyDraftToCommand(draft) === null) return state;
  return {
    ...state,
    kind: "submitting",
    pendingTransportRequestId: transportRequestId,
    notice: null,
  };
}

export function diplomacySubmitSuccess(
  state: DiplomacyScreenState,
  outcome: { readonly commandId: string; readonly bodyType: string },
): DiplomacyScreenState {
  if (state.kind !== "submitting") return state;
  return {
    kind: "submitted",
    revision: state.revision,
    month: state.month,
    projection: state.projection,
    draftCommand: state.draftCommand,
    notice: `${outcome.commandId} (${outcome.bodyType}) queued — the engine applies it on the next turn advance.`,
  };
}

/**
 * Fold a rejection into the state. A rejection carrying a `currentRevision`
 * (stale optimistic-concurrency — `REVISION_MISMATCH`) moves to
 * `rejected-with-revision`; the screen reacts by refreshing the projection.
 * Any other rejection (engine-codes such as `ALREADY_AT_WAR`,
 * `DECLARE_WAR_INVALID_TARGET`, idempotency conflicts) stays on the loaded
 * state with the engine diagnostics as the notice — never fabricated copy.
 */
export function diplomacySubmitRejected(
  state: DiplomacyScreenState,
  rejection: {
    readonly reason: string;
    readonly diagnostics: readonly string[];
    readonly currentRevision?: number;
  },
): DiplomacyScreenState {
  if (state.kind !== "submitting" && state.kind !== "submitted") return state;
  const notice = describeRejection(
    rejection.reason,
    rejection.diagnostics,
    rejection.currentRevision,
  );
  if (rejection.currentRevision !== undefined) {
    return {
      kind: "rejected-with-revision",
      revision: rejection.currentRevision,
      month: state.month,
      projection: state.projection,
      draftCommand: state.draftCommand,
      notice,
    };
  }
  return {
    kind: "loaded",
    revision: state.revision,
    month: state.month,
    projection: state.projection,
    draftCommand: state.draftCommand,
    notice,
  };
}

export function diplomacyTransportFailure(
  state: DiplomacyScreenState,
  message: string,
): DiplomacyScreenState {
  if (state.kind !== "submitting" && state.kind !== "submitted") return state;
  return {
    kind: "loaded",
    revision: state.revision,
    month: state.month,
    projection: state.projection,
    draftCommand: state.draftCommand,
    notice: `TRANSPORT_FAILURE: ${message}`,
  };
}

/** The wire command for the current draft, or null when incomplete. */
export function diplomacyDraftToCommand(draft: DiplomacyDraftCommand): DiplomacyCommandBody | null {
  switch (draft.kind) {
    case "DeclareWar":
      return { type: "DeclareWar", targetNationId: draft.partnerNationId };
    case "AcceptPeace":
      return draft.warId !== undefined ? { type: "AcceptPeace", warId: draft.warId } : null;
    case "FormAlliance":
      return { type: "FormAlliance", partnerNationId: draft.partnerNationId };
    case "BreakAlliance":
      return { type: "BreakAlliance", partnerNationId: draft.partnerNationId };
    case "FormNonAggressionPact":
      return { type: "FormNonAggressionPact", partnerNationId: draft.partnerNationId };
    case "BreakNonAggressionPact":
      return { type: "BreakNonAggressionPact", partnerNationId: draft.partnerNationId };
    case "DeclareBlockade":
      return draft.areaId !== undefined
        ? {
            type: "DeclareBlockade",
            targetNationId: draft.partnerNationId,
            areaId: draft.areaId,
          }
        : null;
  }
}

/** A submit is possible only from a loaded state with a complete draft. */
export function diplomacyCanSubmit(state: DiplomacyScreenState): boolean {
  return (
    state.kind === "loaded" &&
    state.draftCommand !== null &&
    diplomacyDraftToCommand(state.draftCommand) !== null
  );
}

/** Human label for a relation kind. */
export const RELATION_LABELS: Readonly<Record<string, string>> = {
  neutral: "Neutral",
  allied: "Allied",
  at_war: "At war",
  trade_agreement: "Trade agreement",
};
