import type { ContentPack } from "./contentPack.js";

export const PORTUGUESE_PRIMEIRA_LIGA_PACK: ContentPack = {
  id: "portuguese-primeira-liga-licensed",
  displayName: "Portuguese Primeira Liga (licensed)",
  version: "1.0.0",
  contentSource: "LICENSED",
  displayNames: {
    comp_prt_1: { "*": "Primeira Liga" },

    club_prt_1_01: { "*": "Alverca" },
    club_prt_1_02: { "*": "Arouca" },
    club_prt_1_03: { "*": "AVS" },
    club_prt_1_04: { "*": "Benfica" },
    club_prt_1_05: { "*": "Braga" },
    club_prt_1_06: { "*": "Casa Pia" },
    club_prt_1_07: { "*": "Estoril Praia" },
    club_prt_1_08: { "*": "Estrela da Amadora" },
    club_prt_1_09: { "*": "Famalicão" },
    club_prt_1_10: { "*": "Gil Vicente" },
    club_prt_1_11: { "*": "Moreirense" },
    club_prt_1_12: { "*": "Nacional" },
    club_prt_1_13: { "*": "Porto" },
    club_prt_1_14: { "*": "Rio Ave" },
    club_prt_1_15: { "*": "Santa Clara" },
    club_prt_1_16: { "*": "Sporting CP" },
    club_prt_1_17: { "*": "Tondela" },
    club_prt_1_18: { "*": "Vitória de Guimarães" },
  },
  clubColours: {},
  clubBadges: {
    club_prt_1_01: "prt/fc-alverca",
    club_prt_1_02: "prt/fc-arouca",
    club_prt_1_03: "prt/avs-futebol",
    club_prt_1_04: "prt/sl-benfica",
    club_prt_1_05: "prt/sc-braga",
    club_prt_1_06: "prt/casa-pia-ac",
    club_prt_1_07: "prt/gd-estoril-praia",
    club_prt_1_08: "prt/cf-estrela-amadora",
    club_prt_1_09: "prt/fc-famalicao",
    club_prt_1_10: "prt/gil-vicente-fc",
    club_prt_1_11: "prt/moreirense-fc",
    club_prt_1_12: "prt/cd-nacional",
    club_prt_1_13: "prt/fc-porto",
    club_prt_1_14: "prt/rio-ave-fc",
    club_prt_1_15: "prt/cd-santa-clara",
    club_prt_1_16: "prt/sporting-cp",
    club_prt_1_17: "prt/cd-tondela",
    club_prt_1_18: "prt/vitoria-guimaraes-sc",
  },
  stadiums: {
    club_prt_1_01: { name: "Complexo Desportivo FC Alverca", capacity: 6932 },
    club_prt_1_02: { name: "Estádio Municipal de Arouca", capacity: 5000 },
    club_prt_1_03: { name: "Estádio do CD das Aves", capacity: 6230 },
    club_prt_1_04: { name: "Estádio da Luz", capacity: 68100 },
    club_prt_1_05: { name: "Estádio Municipal de Braga", capacity: 30286 },
    club_prt_1_06: { name: "Estádio Municipal de Rio Maior", capacity: 7000 },
    club_prt_1_07: { name: "Estádio António Coimbra da Mota", capacity: 5094 },
    club_prt_1_08: { name: "Estádio José Gomes", capacity: 9288 },
    club_prt_1_09: { name: "Estádio Municipal de Famalicão", capacity: 5186 },
    club_prt_1_10: { name: "Estádio Cidade de Barcelos", capacity: 12046 },
    club_prt_1_11: { name: "Estádio Comendador Joaquim de Almeida Freitas", capacity: 6150 },
    club_prt_1_12: { name: "Estádio da Madeira", capacity: 5200 },
    club_prt_1_13: { name: "Estádio do Dragão", capacity: 50033 },
    club_prt_1_14: { name: "Estádio dos Arcos", capacity: 5300 },
    club_prt_1_15: { name: "Estádio de São Miguel", capacity: 12500 },
    club_prt_1_16: { name: "Estádio José Alvalade", capacity: 52095 },
    club_prt_1_17: { name: "Estádio João Cardoso", capacity: 5000 },
    club_prt_1_18: { name: "Estádio D. Afonso Henriques", capacity: 30029 },
  },
  homeCities: {
    club_prt_1_01: { name: "Alverca", populationBand: "small" },
    club_prt_1_02: { name: "Arouca", populationBand: "small" },
    club_prt_1_03: { name: "Vila das Aves", populationBand: "small" },
    club_prt_1_04: { name: "Lisbon", populationBand: "major" },
    club_prt_1_05: { name: "Braga", populationBand: "large" },
    club_prt_1_06: { name: "Lisbon", populationBand: "major" },
    club_prt_1_07: { name: "Estoril", populationBand: "small" },
    club_prt_1_08: { name: "Amadora", populationBand: "large" },
    club_prt_1_09: { name: "Vila Nova de Famalicão", populationBand: "small" },
    club_prt_1_10: { name: "Barcelos", populationBand: "small" },
    club_prt_1_11: { name: "Guimarães", populationBand: "mid" },
    club_prt_1_12: { name: "Funchal", populationBand: "small" },
    club_prt_1_13: { name: "Porto", populationBand: "major" },
    club_prt_1_14: { name: "Vila do Conde", populationBand: "small" },
    club_prt_1_15: { name: "Ponta Delgada", populationBand: "mid" },
    club_prt_1_16: { name: "Lisbon", populationBand: "major" },
    club_prt_1_17: { name: "Tondela", populationBand: "small" },
    club_prt_1_18: { name: "Guimarães", populationBand: "mid" },
  },
};