/**
 * Writes the shipped commentary file's text into a TypeScript module, so every consumer (the Vite
 * main build, Vitest, Playwright's loader, tsx scripts) gets it from an ordinary import. The file
 * `packages/game-engine/data/events.cfg` stays the source of truth; the generated module is an
 * artifact, and `packages/game-engine/test/match/commentary-file.test.ts` fails when the two differ.
 *
 * Usage: `pnpm generate:commentary` after editing `events.cfg`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const source = path.join(root, "packages/game-engine/data/events.cfg");
const target = path.join(root, "packages/game-engine/src/match/shippedCommentaryText.generated.ts");

const text = readFileSync(source, "utf8");
writeFileSync(
  target,
  [
    "// Generated by `pnpm generate:commentary` from `packages/game-engine/data/events.cfg`. Do not edit:",
    "// edit the .cfg file and regenerate.",
    `export const SHIPPED_COMMENTARY_TEXT: string = ${JSON.stringify(text)};`,
    "",
  ].join("\n"),
);
console.log(`generate-commentary: wrote ${path.relative(root, target)} (${text.length} characters)`);
