import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The club badge library and the manifest that indexes it.
 *
 * The library is one folder per nation holding one PNG per club, `<nation>/<club-slug>.png`, with no
 * league or season anywhere in a path. `manifest.json` beside those folders is generated by the
 * import and committed, one entry per key, so a changed crest reads as a one-line hash diff in review.
 */
export const CLUB_BADGE_LIBRARY_DIR = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "src",
  "renderer",
  "assets",
  "club-badges",
);

export const MANIFEST_FILE = "manifest.json";

export interface ManifestEntry {
  /** `<nation>/<club-slug>`, the address packs map clubs to. */
  readonly key: string;
  /** The badge's path inside the library, always `<key>.png`. */
  readonly file: string;
  readonly sha256: string;
  /** The file's original path inside the dump it was imported from, kept for traceability. */
  readonly source: string;
  /** The adapter that imported it. An import only ever replaces or removes its own adapter's keys. */
  readonly adapter: string;
}

const BADGE_KEY = /^[a-z]{3}\/[a-z0-9]+(?:-[a-z0-9]+)*$/;

export const isBadgeKey = (key: string): boolean => BADGE_KEY.test(key);

/** Code-point order, so the manifest is byte-identical whatever the machine's locale. */
export const compareKeys = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);

export const sha256Of = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");

export const readManifest = (libraryDir: string): ReadonlyArray<ManifestEntry> => {
  const file = path.join(libraryDir, MANIFEST_FILE);
  if (!existsSync(file)) return [];
  const parsed: ReadonlyArray<ManifestEntry> = JSON.parse(readFileSync(file, "utf8"));
  return parsed;
};

export const serializeManifest = (entries: ReadonlyArray<ManifestEntry>): string =>
  `${JSON.stringify(
    [...entries]
      .sort((a, b) => compareKeys(a.key, b.key))
      .map(({ key, file, sha256, source, adapter }) => ({ key, file, sha256, source, adapter })),
    null,
    2,
  )}\n`;

export const writeManifest = (libraryDir: string, entries: ReadonlyArray<ManifestEntry>): void => {
  mkdirSync(libraryDir, { recursive: true });
  writeFileSync(path.join(libraryDir, MANIFEST_FILE), serializeManifest(entries));
};

/** Every badge file in the library as a POSIX path relative to it. Dotfiles (`.DS_Store`) are not library content. */
export const libraryFiles = (libraryDir: string): ReadonlyArray<string> =>
  existsSync(libraryDir)
    ? readdirSync(libraryDir, { recursive: true, encoding: "utf8" })
        .map((entry) => entry.split(path.sep))
        .filter((segments) => !segments.some((segment) => segment.startsWith(".")))
        .map((segments) => segments.join("/"))
        .filter((file) => file !== MANIFEST_FILE && statSync(path.join(libraryDir, file)).isFile())
        .sort(compareKeys)
    : [];

export type IntegrityProblem =
  | { readonly _tag: "MissingFile"; readonly key: string; readonly file: string }
  | { readonly _tag: "UnindexedFile"; readonly file: string }
  | { readonly _tag: "StaleHash"; readonly key: string; readonly file: string }
  | { readonly _tag: "MalformedEntry"; readonly key: string; readonly file: string }
  | { readonly _tag: "UnknownPackKey"; readonly packId: string; readonly clubId: string; readonly key: string };

/** The part of a content pack the library answers to. Structural, so a test can pass a two-line pack. */
export interface BadgeMappingPack {
  readonly id: string;
  readonly clubBadges: Readonly<Record<string, string>>;
}

/**
 * Everything on which the manifest, the files on disk and the packs' mappings disagree. Empty means
 * the library is sound: every entry has its file at `<key>.png` with the recorded hash, every file
 * has an entry, and every key a pack maps a club to exists.
 */
export const checkLibraryIntegrity = (
  libraryDir: string,
  packs: ReadonlyArray<BadgeMappingPack>,
): ReadonlyArray<IntegrityProblem> => {
  const entries = readManifest(libraryDir);
  const problems: Array<IntegrityProblem> = [];

  for (const { key, file, sha256 } of entries) {
    if (!isBadgeKey(key) || file !== `${key}.png`) {
      problems.push({ _tag: "MalformedEntry", key, file });
    } else if (!existsSync(path.join(libraryDir, file))) {
      problems.push({ _tag: "MissingFile", key, file });
    } else if (sha256Of(readFileSync(path.join(libraryDir, file))) !== sha256) {
      problems.push({ _tag: "StaleHash", key, file });
    }
  }

  const indexed = new Set(entries.map((entry) => entry.file));
  for (const file of libraryFiles(libraryDir)) {
    if (!indexed.has(file)) problems.push({ _tag: "UnindexedFile", file });
  }

  const keys = new Set(entries.map((entry) => entry.key));
  for (const pack of packs) {
    for (const [clubId, key] of Object.entries(pack.clubBadges)) {
      if (!keys.has(key)) problems.push({ _tag: "UnknownPackKey", packId: pack.id, clubId, key });
    }
  }

  return problems;
};
